### ISSUE TITLE
Having trouble with this plugin

### ISSUE THREAD

**Issue by nalinib** [Liverpool-Victoria/gradle-weblogic-plugin#5]
Hello,

I downloaded your zip file to try to get the plugin tested on Weblogic 12c and I got the below error.   Can you please take a look what is wrong.

==========================
$ gradle tasks --info
Starting Build
Settings evaluated using empty settings script.
Projects loaded. Root project using build file 'C:\gradle-projects\gradle-weblogic-plugin-master\gradle-weblogic-plugin-master\demo\build.gradle'.
Included projects: [root project 'demo']
Evaluating root project 'demo' using build file 'C:\gradle-projects\gradle-weblogic-plugin-master\gradle-weblogic-plugin-master\demo\build.gradle'.
Resource missing. [HTTP HEAD: http://repo1.maven.org/maven2/com/lv/plugins/gradle-weblogic-plugin/0.3/gradle-weblogic-plugin-0.3.pom]
Resource missing. [HTTP HEAD: http://repo1.maven.org/maven2/com/lv/plugins/gradle-weblogic-plugin/0.3/gradle-weblogic-plugin-0.3.jar]

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'demo'.
> Could not resolve all dependencies for configuration ':classpath'.
   > Could not find com.lv.plugins:gradle-weblogic-plugin:0.3.
     Required by:
         :demo:unspecified

* Try:
Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output.

BUILD FAILED

Total time: 2.401 secs

**Comment by willis7** [comment]
@nalinib Hi, the problem is that the demo is looking for the plugin in maven central. Unfortunately I haven't yet published it there. I will make the change this evening and let you know when its good to go. Sorry, this was a short sighted omission on my part as I have it staged in my company Nexus repo.

**Comment by willis7** [comment]
@nalinib the incorrect maven repository was added to the demo project. Let me know how your testing goes, and feel free to ask any further questions.

**Comment by nalinib** [comment]
No worries.  I got the correct example from your API documentation and got the your demo working.   This plugin should also work for EAR deployment, correct ?  Thanks !

**Comment by willis7** [comment]
Yes, this is just a wrapper around the ant task, so you should find it has the same features.

https://docs.oracle.com/cd/E13222_01/wls/docs92/programming/wldeploy.html
